main:
  cog zmp:
    legends:
      - { key: st_originActCog, id: [0-2]}
      - { key: st_originRefCog, id: [0-2]}
      - { key: st_originRefZmp, id: [0-2]}
      - { key: st_originNewZmp, id: [0-2]}
      - { key: st_originActZmp, id: [0-2]}
      - { key: abc_originActCog, id: [0-2]}
      - { key: abc_originRefCog, id: [0-2]}
      - { key: abc_originRefZmp, id: [0-2]}
      - { key: abc_originNewZmp, id: [0-2]}
      - { key: abc_originActZmp, id: [0-2]}
      - { key: abst_footActCog, id: [0-2]}
      - { key: abst_footGenCog, id: [0-2]}
      - { key: abst_footGenZmp, id: [0-2]}
      - { key: abst_footModZmp, id: [0-2]}
      - { key: abst_footActZmp, id: [0-2]}
    bottom_label:

  cog velocity:
    legends:
      - { key: st_originActCogVel, id: [0-2]}
      - { key: st_originRefCogVel, id: [0-2]}
      - { key: abc_originActCogVel, id: [0-2]}
      - { key: abc_originRefCogVel, id: [0-2]}
      - { key: abst_footActCogVel, id: [0-2]}
      - { key: abst_genCogVel, id: [0-2]}
    bottom_label:

  angular momentum:
    legends:
      - { key: abst_genAngularMomentum, id: [0-2]}

  # root-link relative zmp:
  #   legends:
  #     - { key: st_zmp, id: [0-1] }
  #     - { key: abc_zmpOut, id: [0-1] }
  #   bottom_label:
  #   # newline: false

  base pos:
    legends:
      - { key: abc_basePos, id: [0-1] }
      - { key: abst_basePos, id: [0-1] }
    bottom_label:
    newline: false

  world cog/zmp:
    legends:
      # - { key: abc_zmpOut, id: [0-1] }
      # - { key: st_zmp, id: [0-1] }
      - { key: abc_refCog, id: [0-1] }
      - { key: abc_refZmp, id: [0-1] }
      # - { key: st_refZmp, id: [0-1] }
      # - { key: st_actZmp, id: [0-1] }
      - { key: abst_genCog, id: [0-1] }
      - { key: abst_nominalZmp, id: [0-1] }
      - { key: abst_genZmp, id: [0-1] }
      - { key: abst_genEndCp, id: [0-1] }
      - { key: abst_genCp, id: [0-1] }
      - { key: abst_genZmpTf, id: [0-1] }
      - { key: abst_actZmpTf, id: [0-1] }
    bottom_label:
    # newline: false

# rpy
  base rpy:
    legends:
      - { key: sh_baseRpyOut, id: [0-2] }
      - { key: st_currentBaseRpy, id: [0-2] }
      - { key: st_actBaseRpy, id: [0-2] }
      - { key: abc_currentBaseRpy, id: [0-2] }
      - { key: abc_actBaseRpy, id: [0-2] }
      - { key: abst_currentBaseRpy, id: [0-2] }
      - { key: abst_actBaseRpy, id: [0-2] }

  base rpy vel:
    legends:
      - { key: sh_baseRpyVel, id: [0-2] }
      - { key: st_currentBaseRpyVel, id: [0-2] }
      - { key: st_actBaseRpyVel, id: [0-2] }
      - { key: abc_currentBaseRpyVel, id: [0-2] }
      - { key: abc_actBaseRpyVel, id: [0-2] }
      - { key: abst_currentBaseRpyVel, id: [0-2] }
      - { key: abst_actBaseRpyVel, id: [0-2] }
